---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jujufg
  labels:
    app: jujufg
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jujufg
  template:
    metadata:
      labels:
        app: jujufg
    spec:
      containers:
        - name: jujufg
          image: docker.io/phengbunath/jujufg:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080